### ISSUE TITLE
Question: how to identify the app bots in Azure

### ISSUE THREAD

**Issue by alexabramkin** [OfficeDev/microsoft-teams-apps-poll#5]
Deployment Guide documentation at Step1.6 states "An AAD custom app, Bot are programmatically created in your tenant to power the Poll message extension app in Teams."
After successfully deploying app in the tenant and using it in Teams unable to locate corresponding bot in Azure.
Could you please provide documentation on identifying Bot and related resources created in Azure by npm run deploy command?

**Comment by yogesh-MS** [comment]
Bot is stored in the M365 subscription. So User does not have access to it.
