### ISSUE TITLE
Who created Poll (user Name and Surname)?

### ISSUE THREAD

**Issue by algimantasrusteikalitrail** [OfficeDev/microsoft-teams-apps-poll#8]
Hello,
By looking in "Key features" on "Poll creation" section in screenshot I see that Created polls have creator name in Title "Alex Wilber via Poll".
However when users create Polls we only see "Poll" in the Title?

**Comment by yogesh-MS** [comment]
when user creates Poll. The Poll is in draft state so will be shown as  "Poll" . Once it is created, then Poll will be shown with creator name.
